# from django.core.exceptions import ValidationError


class AmenityValidator:
    def __init__(self): ...

    def __call__(self):
        return True
